
import React from 'react';
import { X, Book, Heart, Zap, Skull, Shield, Briefcase } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

export const TrainerHandbookModal: React.FC<Props> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-slate-900/50 flex items-center justify-center z-[150] backdrop-blur-sm p-4 animate-fade-in">
      <div className="bg-white rounded-2xl w-full max-w-2xl h-[80vh] flex flex-col shadow-2xl overflow-hidden border-4 border-slate-200">
         <div className="bg-indigo-600 p-4 text-white flex justify-between items-center shadow-md shrink-0">
            <div className="flex items-center gap-2">
               <Book className="text-indigo-200" />
               <h2 className="text-xl font-bold tracking-tight">Trainer's Handbook</h2>
            </div>
            <button onClick={onClose} className="hover:bg-indigo-500 p-1 rounded-full transition-colors"><X /></button>
         </div>

         <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-slate-50">
            
            <section>
               <h3 className="text-lg font-black text-slate-800 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <span className="text-2xl">🎯</span> The Goal
               </h3>
               <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                  <p className="text-slate-600 leading-relaxed">
                    Welcome, Trainer! Your goal in the Region of Econo is simple: <strong>Keep your FinMon alive and help it evolve.</strong> Your FinMon is a spiritual reflection of your bank account. When you thrive, it thrives. When you struggle, it suffers.
                  </p>
               </div>
            </section>

            <section>
               <h3 className="text-lg font-black text-slate-800 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <span className="text-2xl">⚙️</span> Core Mechanics
               </h3>
               <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-white p-4 rounded-xl border border-green-200 shadow-sm">
                     <h4 className="font-bold text-green-700 mb-2 flex items-center gap-2"><Heart size={18}/> HP (Budget)</h4>
                     <ul className="text-sm text-slate-600 space-y-1">
                        <li>• Starts full (Income) every month.</li>
                        <li>• <strong>Expenses</strong> are "Attacks" that lower HP.</li>
                        <li>• <strong>Game Over:</strong> HP hits 0 (Overdraft).</li>
                     </ul>
                  </div>
                  <div className="bg-white p-4 rounded-xl border border-yellow-200 shadow-sm">
                     <h4 className="font-bold text-yellow-700 mb-2 flex items-center gap-2"><Zap size={18}/> XP (Savings)</h4>
                     <ul className="text-sm text-slate-600 space-y-1">
                        <li>• Generated by saving money.</li>
                        <li>• <strong>Level Up:</strong> Gain enough XP.</li>
                        <li>• <strong>Evolution:</strong> Reach major milestones (e.g. $10k).</li>
                     </ul>
                  </div>
                  <div className="bg-white p-4 rounded-xl border border-purple-200 shadow-sm md:col-span-2">
                     <h4 className="font-bold text-purple-700 mb-2 flex items-center gap-2"><Skull size={18}/> Status Effects (Debt)</h4>
                     <ul className="text-sm text-slate-600 space-y-1">
                        <li>• <strong>Poison:</strong> High-interest debt drains HP every turn.</li>
                        <li>• <strong>Paralysis:</strong> Late fees prevent using items.</li>
                     </ul>
                  </div>
               </div>
            </section>

             <section>
               <h3 className="text-lg font-black text-slate-800 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <span className="text-2xl">🎒</span> Inventory
               </h3>
               <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex flex-col gap-3">
                  <div className="flex gap-3">
                     <div className="bg-blue-100 p-2 rounded-lg text-blue-600 h-fit"><Briefcase size={20}/></div>
                     <div>
                        <h4 className="font-bold text-slate-800">Potions</h4>
                        <p className="text-sm text-slate-600">Side hustles or bonuses that restore HP instantly.</p>
                     </div>
                  </div>
                  <div className="flex gap-3">
                     <div className="bg-slate-100 p-2 rounded-lg text-slate-600 h-fit"><Shield size={20}/></div>
                     <div>
                        <h4 className="font-bold text-slate-800">Shields</h4>
                        <p className="text-sm text-slate-600">Insurance policies that block "Critical Hits" (Emergencies).</p>
                     </div>
                  </div>
               </div>
            </section>

         </div>
         
         <div className="p-4 border-t border-slate-200 bg-slate-50">
            <button onClick={onClose} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-xl transition-colors shadow-md">
               Got it!
            </button>
         </div>
      </div>
    </div>
  );
};
